"""Coverage report used by the CLI, docs generator and API."""

from __future__ import annotations

import sqlite3

from rotom_dex.errors import NotFound
from rotom_dex.repositories.common import coverage_rows, overall_status, rows, snapshot_id


def coverage_report(db: sqlite3.Connection, game: str | None = None) -> dict:
    games = rows(
        db,
        """SELECT g.id, g.slug, g.name, g.support_tier, v.slug AS version_group,
                        v.generation_id AS generation FROM game_versions g
                        JOIN version_groups v ON v.id=g.version_group_id ORDER BY v.ord, g.id""",
    )
    if game is not None:
        games = [g for g in games if g["slug"] == game.lower()]
        if not games:
            raise NotFound(f"Unknown game: {game}")
    report = []
    for g in games:
        coverage = coverage_rows(db, g["id"])
        report.append(
            {
                **g,
                "coverage_status": overall_status(coverage) if coverage else "missing",
                "features": [{k: c[k] for k in ("feature", "status", "note")} for c in coverage],
                "issues": rows(
                    db,
                    "SELECT id, feature, subject, kind, description FROM data_issues WHERE game_id=? ORDER BY id",
                    (g["id"],),
                ),
            }
        )
    global_issues = rows(
        db,
        "SELECT id, feature, subject, kind, description FROM data_issues WHERE game_id IS NULL ORDER BY id",
    )
    return {"snapshot_id": snapshot_id(db), "games": report, "global_issues": global_issues}


def render_markdown(report: dict) -> str:
    lines = [
        "# Coverage report",
        "",
        f"Snapshot `{report['snapshot_id'][:16]}…`. Generated by `rotom coverage --format markdown`; do not edit by hand.",
        "",
    ]
    features = sorted({f["feature"] for g in report["games"] for f in g["features"]})
    imported = [g for g in report["games"] if g["features"]]
    others = [g for g in report["games"] if not g["features"]]
    symbols = {"complete": "●", "partial": "◐", "missing": "○", "disputed": "✕"}
    lines += [
        "Legend: ● complete · ◐ partial · ○ missing · ✕ disputed. 'Complete' is relative to the pinned source and reviewed packs.",
        "",
        "| Game | Tier | Gen | " + " | ".join(features) + " |",
        "| --- | --- | --- | " + " | ".join("---" for _ in features) + " |",
    ]
    for g in imported:
        status = {f["feature"]: f["status"] for f in g["features"]}
        lines.append(f"| {g['slug']} | {g['support_tier']} | {g['generation']} | " + " | ".join(symbols.get(status.get(f, "missing"), "?") for f in features) + " |")
    lines += ["", "## Games without imported facts", ""]
    for g in others:
        lines.append(f"- `{g['slug']}` ({g['support_tier']})")
    lines += ["", "## Feature notes", ""]
    for g in imported:
        lines += [f"### {g['slug']}", ""]
        for f in g["features"]:
            lines.append(f"- **{f['feature']}** ({f['status']}): {f['note']}")
        if g["issues"]:
            lines += ["", "Recorded issues:", ""]
            for issue in g["issues"]:
                lines.append(f"- `{issue['id']}` [{issue['kind']}] {issue['description']}")
        lines.append("")
    if report["global_issues"]:
        lines += ["## Source-wide issues", ""]
        for issue in report["global_issues"]:
            lines.append(f"- `{issue['id']}` [{issue['kind']}] {issue['description']}")
    return "\n".join(lines) + "\n"


def coverage_matrix(db: sqlite3.Connection, notes: bool = False) -> dict:
    """The whole game x feature grid in one response, for the game selector.

    Reshapes `coverage_report` rather than re-querying. Games with no coverage rows are kept and
    labelled `has_facts: false`: `catalog` and `excluded` are a stated support policy, not missing
    data. Per-cell notes are opt-in because they are most of the payload; `GET /api/coverage?game=`
    carries them for one game when a cell is opened.
    """
    report = coverage_report(db, None)
    features = sorted({f["feature"] for g in report["games"] for f in g["features"]})
    games = []
    for g in report["games"]:
        statuses = {f["feature"]: ({"status": f["status"], "note": f["note"]} if notes else {"status": f["status"]}) for f in g["features"]}
        games.append(
            {
                "slug": g["slug"],
                "name": g["name"],
                "support_tier": g["support_tier"],
                "generation": g["generation"],
                "version_group": g["version_group"],
                "coverage_status": g["coverage_status"],
                "has_facts": bool(g["features"]),
                "features": statuses,
                "counts": {s: sum(1 for f in g["features"] if f["status"] == s) for s in ("complete", "partial", "missing", "disputed")},
                "issue_count": len(g["issues"]),
            }
        )
    return {
        "features": features,
        "games": games,
        "global_issues": report["global_issues"],
    }


# Features that decide whether a game is usable for a playthrough, in the order a curator would
# tackle them. Everything else comes from the pinned source and needs no review.
CURATED_FEATURES = ("progression", "boss-teams", "location-gates", "shops", "item-acquisition", "tutors", "encounters", "evolution", "mechanics")

BACKLOG_HEADER = """# Coverage backlog

Generated by `rotom coverage --format backlog`; do not edit by hand. Every line is derived from the
`coverage` and `data_issues` tables of a built database, so it cannot drift from what is actually
reviewed.

A game listed here is **not** a game that is broken. Facts from the pinned source are imported for
every game below; what is missing is the *curated* layer -- the reviewed progression, rosters,
access gates and shops that turn a catalogue into a playthrough companion. Missing means missing,
never unobtainable.
"""


def render_backlog(report: dict) -> str:
    games = report["games"]
    lines = [BACKLOG_HEADER, f"Snapshot `{report['snapshot_id'][:16]}…`.\n"]

    def status_of(game: dict, feature: str) -> str:
        return next((f["status"] for f in game["features"] if f["feature"] == feature), "missing")

    ready = [g for g in games if status_of(g, "progression") == "complete" and status_of(g, "boss-teams") == "complete"]
    started = [g for g in games if g not in ready and any(status_of(g, f) != "missing" for f in ("progression", "boss-teams", "location-gates"))]
    untouched = [g for g in games if g not in ready and g not in started and g["features"]]

    lines.append("## Where each game stands\n")
    lines.append("| Tier | Games | What that means |")
    lines.append("| --- | --- | --- |")
    lines.append(
        f"| Reviewed end to end | {len(ready)}: {', '.join(g['slug'] for g in ready) or '—'} "
        "| Connected main-story milestones to a declared end, and a roster for every badge, Elite Four and Champion milestone. |"
    )
    lines.append(
        f"| Partly curated | {len(started)}: {', '.join(g['slug'] for g in started) or '—'} | Some curated content exists but the story chain or the rosters are incomplete. |"
    )
    lines.append(f"| Source facts only | {len(untouched)} games | Imported from the pinned source, with no reviewed progression, rosters, gates or shops. |")
    lines.append("")

    lines.append("## What each reviewed game still needs\n")
    for game in ready + started:
        gaps = [f"`{f}` — {status_of(game, f)}" for f in CURATED_FEATURES if status_of(game, f) != "complete"]
        lines.append(f"### {game['name']} (`{game['slug']}`)\n")
        if gaps:
            lines.append("Incomplete features:\n")
            lines.extend(f"- {gap}" for gap in gaps)
            lines.append("")
        for issue in game["issues"]:
            lines.append(f"- **{issue['feature']}** ({issue['kind']}): {issue['description']}")
        lines.append("")

    lines.append("## What every uncurated game needs\n")
    lines.append("The same six pieces of work, in this order:\n")
    lines.append("1. `progression` — a connected chain of reviewed milestones ending at a declared `main_story_end`.")
    lines.append("2. `location-gates` — one reviewed access condition per location that has encounters, which is what")
    lines.append("   lets an encounter be settled by recorded progress instead of staying unknown forever.")
    lines.append("3. `boss-teams` — a reviewed roster for every badge, Elite Four and Champion milestone.")
    lines.append("4. `item-acquisition` — TM, HM and key item locations tied to those milestones.")
    lines.append("5. `shops` — inventories and the badge count that unlocks each one.")
    lines.append("6. `tutors` — locations and costs, which no game in this snapshot has.\n")
    lines.append(f"Games in this tier: {', '.join(g['slug'] for g in untouched)}.\n")

    if report["global_issues"]:
        lines.append("## Gaps in the source itself\n")
        for issue in report["global_issues"]:
            lines.append(f"- **{issue['feature']}** ({issue['kind']}): {issue['description']}")
        lines.append("")
    return "\n".join(lines)
