"""Coverage report used by the CLI, docs generator and API."""

from __future__ import annotations

import sqlite3

from rotom_dex.repositories.common import coverage_rows, overall_status, rows, snapshot_id


def coverage_report(db: sqlite3.Connection, game: str | None = None) -> dict:
    games = rows(
        db,
        """SELECT g.id, g.slug, g.name, g.support_tier, v.slug AS version_group,
                        v.generation_id AS generation FROM game_versions g
                        JOIN version_groups v ON v.id=g.version_group_id ORDER BY v.ord, g.id""",
    )
    if game is not None:
        games = [g for g in games if g["slug"] == game.lower()]
        if not games:
            raise ValueError(f"Unknown game: {game}")
    report = []
    for g in games:
        coverage = coverage_rows(db, g["id"])
        report.append(
            {
                **g,
                "coverage_status": overall_status(coverage) if coverage else "missing",
                "features": [{k: c[k] for k in ("feature", "status", "note")} for c in coverage],
                "issues": rows(
                    db,
                    "SELECT id, feature, subject, kind, description FROM data_issues WHERE game_id=? ORDER BY id",
                    (g["id"],),
                ),
            }
        )
    global_issues = rows(
        db,
        "SELECT id, feature, subject, kind, description FROM data_issues WHERE game_id IS NULL ORDER BY id",
    )
    return {"snapshot_id": snapshot_id(db), "games": report, "global_issues": global_issues}


def render_markdown(report: dict) -> str:
    lines = [
        "# Coverage report",
        "",
        f"Snapshot `{report['snapshot_id'][:16]}…`. Generated by `rotom coverage --format markdown`; do not edit by hand.",
        "",
    ]
    features = sorted({f["feature"] for g in report["games"] for f in g["features"]})
    imported = [g for g in report["games"] if g["features"]]
    others = [g for g in report["games"] if not g["features"]]
    symbols = {"complete": "●", "partial": "◐", "missing": "○", "disputed": "✕"}
    lines += [
        "Legend: ● complete · ◐ partial · ○ missing · ✕ disputed. 'Complete' is relative to the pinned source and reviewed packs.",
        "",
        "| Game | Tier | Gen | " + " | ".join(features) + " |",
        "| --- | --- | --- | " + " | ".join("---" for _ in features) + " |",
    ]
    for g in imported:
        status = {f["feature"]: f["status"] for f in g["features"]}
        lines.append(f"| {g['slug']} | {g['support_tier']} | {g['generation']} | " + " | ".join(symbols.get(status.get(f, "missing"), "?") for f in features) + " |")
    lines += ["", "## Games without imported facts", ""]
    for g in others:
        lines.append(f"- `{g['slug']}` ({g['support_tier']})")
    lines += ["", "## Feature notes", ""]
    for g in imported:
        lines += [f"### {g['slug']}", ""]
        for f in g["features"]:
            lines.append(f"- **{f['feature']}** ({f['status']}): {f['note']}")
        if g["issues"]:
            lines += ["", "Recorded issues:", ""]
            for issue in g["issues"]:
                lines.append(f"- `{issue['id']}` [{issue['kind']}] {issue['description']}")
        lines.append("")
    if report["global_issues"]:
        lines += ["## Source-wide issues", ""]
        for issue in report["global_issues"]:
            lines.append(f"- `{issue['id']}` [{issue['kind']}] {issue['description']}")
    return "\n".join(lines) + "\n"
